filebeat.inputs:
  - type: filestream
    enabled: true
    paths:
      - /var/log/apache2/access.log
      - /var/log/apache2/error.log

    fields:
      service: dvwa
    fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info

setup.kibana:
  host: "kibana:5601"