input {
  beats {
    port => 5044
  }
}

filter {


  grok {
    match => {
      "message" => "%{IPORHOST:clientip} %{DATA:ident} %{DATA:auth} \[%{HTTPDATE:timestamp}\] \"%{WORD:method} %{URIPATHPARAM:request} HTTP/%{NUMBER:http_version}\" %{NUMBER:response} %{NUMBER:bytes}"
    }
    tag_on_failure => ["_grok_fail"]
  }

  mutate {
    convert => {
      "response" => "integer"
      "bytes" => "integer"
    }
  }


  if [request] =~ "/login" {
    mutate {
      add_tag => ["login_attempt"]
    }
  }


  if [response] == 401 or [response] == 403 {
    mutate {
      add_tag => ["auth_failure"]
    }
  }


  date {
    match => ["timestamp", "dd/MMM/yyyy:HH:mm:ss Z"]
    target => "@timestamp"
  }


  geoip {
    source => "clientip"
    target => "geo"
  }
}

output {

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "dvwa-logs"
  }

  stdout {
    codec => rubydebug
  }
}